spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:weatherdb
    username: ${TEST_DB_USER:test-db-user}
    password: ${TEST_DB_PWD:test-db-pwd}
  config:
    import: optional:file:.env[.properties]

weather-stack:
  api-url: http://api.weatherstack.com/current
  api-key: ${WEATHER_STACK_API_KEY:default-key}
  cache-name: weathers
  api-call-limit: 10
  cache-ttl: 60000 #1 minute


